#!/bin/bash
source helpers

cd etc
symlink_if_not_exists .bash_profile
symlink_if_not_exists .gitconfig
symlink_if_not_exists .gitignore_global
symlink_if_not_exists .tmux.conf
symlink_if_not_exists .vimrc
symlink_if_not_exists .zshrc
cd ..

mkdir -p .vim/autoload .vim/bundle
clone_if_not_exists https://github.com/VundleVim/Vundle.vim.git .vim/bundle/Vundle.vim
clone_if_not_exists https://github.com/romkatv/gitstatus.git ~/gitstatus
symlink_if_not_exists .vim

vim +PluginInstall +qall

mkdir -p ~/.tmp
