#!/bin/bash
source helpers

cd etc
symlink_if_not_exists .bash_profile
symlink_if_not_exists .gitconfig
symlink_if_not_exists .tmux.conf
symlink_if_not_exists .vimrc
symlink_if_not_exists .zshrc
symlink_if_not_exists .vim
cd ..

mkdir -p .vim/autoload .vim/bundle

vim +PluginInstall +qall

